### ISSUE TITLE
Gym error

### ISSUE THREAD

**Issue by GoingMyWay** [SamsungLabs/tqc_pytorch#5]
I was trying to run the code. By following the yml file in this repo and installing `gym==0.12.5`. I got the following error when running the code.

```
user@63a385b1ec08:~/app$ bash scripts/run_train.sh 
Traceback (most recent call last):
  File "main.py", line 113, in <module>
    main(args, results_dir, models_dir, args.prefix)
  File "main.py", line 23, in main
    env = gym.make(args.env).unwrapped
  File "/home/user/miniconda3/envs/env/lib/python3.6/site-packages/gym/envs/registration.py", line 156, in make
    return registry.make(id, **kwargs)
  File "/home/user/miniconda3/envs/env/lib/python3.6/site-packages/gym/envs/registration.py", line 100, in make
    spec = self.spec(path)
  File "/home/user/miniconda3/envs/env/lib/python3.6/site-packages/gym/envs/registration.py", line 129, in spec
    raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))
gym.error.Error: Attempted to look up malformed environment ID: b'Walker2d'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)
```

How can I fix it?

**Comment by brickerino** [comment]
Hi.

>raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))
>gym.error.Error: Attempted to look up malformed environment ID: b'Walker2d'. (Currently all IDs must be of the form ^(?:[\w:-]+\/)?([\w:.-]+)-v(\d+)$.)

It says that the env name should be 'Walker2d-v3', not just 'Walker2d'.

**Comment by GoingMyWay** [comment]
> Hi.
> 
> > raise error.Error('Attempted to look up malformed environment ID: {}. (Currently all IDs must be of the form {}.)'.format(id.encode('utf-8'), env_id_re.pattern))
> > gym.error.Error: Attempted to look up malformed environment ID: b'Walker2d'. (Currently all IDs must be of the form ^(?:[\w:-]+/)?([\w:.-]+)-v(\d+)$.)
> 
> It says that the env name should be 'Walker2d-v3', not just 'Walker2d'.

Yes. Besides, Walker2d-v3, I also found Walker2d-v2. Which one is better?

**Comment by brickerino** [comment]
As far as I remember v3 is rewritten version of v2, same environment, different source code. We have used v3.

**Comment by GoingMyWay** [comment]
> As far as I remember v3 is rewritten version of v2, same environment, different source code. We have used v3.

Thank you. I will use v3 to reproduce the results.
